// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldNameFirst holds the string denoting the name_first field in the database.
	FieldNameFirst = "name_first"
	// FieldNameLast holds the string denoting the name_last field in the database.
	FieldNameLast = "name_last"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldRootAdmin holds the string denoting the root_admin field in the database.
	FieldRootAdmin = "root_admin"
	// EdgeClanky holds the string denoting the clanky edge name in mutations.
	EdgeClanky = "clanky"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ClankyTable is the table that holds the clanky relation/edge.
	ClankyTable = "clankies"
	// ClankyInverseTable is the table name for the Clanky entity.
	// It exists in this package in order to avoid circular dependency with the "clanky" package.
	ClankyInverseTable = "clankies"
	// ClankyColumn is the table column denoting the clanky relation/edge.
	ClankyColumn = "autor_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldEmail,
	FieldNameFirst,
	FieldNameLast,
	FieldPassword,
	FieldDeleted,
	FieldRootAdmin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultDeleted holds the default value on creation for the "deleted" field.
	DefaultDeleted bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByNameFirst orders the results by the name_first field.
func ByNameFirst(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameFirst, opts...).ToFunc()
}

// ByNameLast orders the results by the name_last field.
func ByNameLast(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameLast, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByDeleted orders the results by the deleted field.
func ByDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleted, opts...).ToFunc()
}

// ByRootAdmin orders the results by the root_admin field.
func ByRootAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRootAdmin, opts...).ToFunc()
}

// ByClankyCount orders the results by clanky count.
func ByClankyCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newClankyStep(), opts...)
	}
}

// ByClanky orders the results by clanky terms.
func ByClanky(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClankyStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newClankyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClankyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ClankyTable, ClankyColumn),
	)
}
