// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClankiesColumns holds the columns for the "clankies" table.
	ClankiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "nazev", Type: field.TypeString},
		{Name: "typ", Type: field.TypeInt},
		{Name: "date", Type: field.TypeTime},
		{Name: "verejne", Type: field.TypeBool},
		{Name: "text", Type: field.TypeString, Size: 2147483647},
		{Name: "image", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "autor_id", Type: field.TypeInt},
	}
	// ClankiesTable holds the schema information for the "clankies" table.
	ClankiesTable = &schema.Table{
		Name:       "clankies",
		Columns:    ClankiesColumns,
		PrimaryKey: []*schema.Column{ClankiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "clankies_users_clanky",
				Columns:    []*schema.Column{ClankiesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "name_first", Type: field.TypeString, Nullable: true},
		{Name: "name_last", Type: field.TypeString, Nullable: true},
		{Name: "password", Type: field.TypeString},
		{Name: "deleted", Type: field.TypeBool, Default: false},
		{Name: "root_admin", Type: field.TypeInt},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClankiesTable,
		SettingsTable,
		UsersTable,
	}
)

func init() {
	ClankiesTable.ForeignKeys[0].RefTable = UsersTable
}
