// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/predicate"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClankyUpdate is the builder for updating Clanky entities.
type ClankyUpdate struct {
	config
	hooks    []Hook
	mutation *ClankyMutation
}

// Where appends a list predicates to the ClankyUpdate builder.
func (cu *ClankyUpdate) Where(ps ...predicate.Clanky) *ClankyUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetNazev sets the "nazev" field.
func (cu *ClankyUpdate) SetNazev(s string) *ClankyUpdate {
	cu.mutation.SetNazev(s)
	return cu
}

// SetNillableNazev sets the "nazev" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableNazev(s *string) *ClankyUpdate {
	if s != nil {
		cu.SetNazev(*s)
	}
	return cu
}

// SetAutorID sets the "autor_id" field.
func (cu *ClankyUpdate) SetAutorID(i int) *ClankyUpdate {
	cu.mutation.SetAutorID(i)
	return cu
}

// SetNillableAutorID sets the "autor_id" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableAutorID(i *int) *ClankyUpdate {
	if i != nil {
		cu.SetAutorID(*i)
	}
	return cu
}

// SetDate sets the "date" field.
func (cu *ClankyUpdate) SetDate(t time.Time) *ClankyUpdate {
	cu.mutation.SetDate(t)
	return cu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableDate(t *time.Time) *ClankyUpdate {
	if t != nil {
		cu.SetDate(*t)
	}
	return cu
}

// SetVerejne sets the "verejne" field.
func (cu *ClankyUpdate) SetVerejne(b bool) *ClankyUpdate {
	cu.mutation.SetVerejne(b)
	return cu
}

// SetNillableVerejne sets the "verejne" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableVerejne(b *bool) *ClankyUpdate {
	if b != nil {
		cu.SetVerejne(*b)
	}
	return cu
}

// SetText sets the "text" field.
func (cu *ClankyUpdate) SetText(s string) *ClankyUpdate {
	cu.mutation.SetText(s)
	return cu
}

// SetNillableText sets the "text" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableText(s *string) *ClankyUpdate {
	if s != nil {
		cu.SetText(*s)
	}
	return cu
}

// SetImage sets the "image" field.
func (cu *ClankyUpdate) SetImage(s string) *ClankyUpdate {
	cu.mutation.SetImage(s)
	return cu
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (cu *ClankyUpdate) SetNillableImage(s *string) *ClankyUpdate {
	if s != nil {
		cu.SetImage(*s)
	}
	return cu
}

// ClearImage clears the value of the "image" field.
func (cu *ClankyUpdate) ClearImage() *ClankyUpdate {
	cu.mutation.ClearImage()
	return cu
}

// SetAutor sets the "autor" edge to the User entity.
func (cu *ClankyUpdate) SetAutor(u *User) *ClankyUpdate {
	return cu.SetAutorID(u.ID)
}

// Mutation returns the ClankyMutation object of the builder.
func (cu *ClankyUpdate) Mutation() *ClankyMutation {
	return cu.mutation
}

// ClearAutor clears the "autor" edge to the User entity.
func (cu *ClankyUpdate) ClearAutor() *ClankyUpdate {
	cu.mutation.ClearAutor()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClankyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClankyUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClankyUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClankyUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClankyUpdate) check() error {
	if v, ok := cu.mutation.Nazev(); ok {
		if err := clanky.NazevValidator(v); err != nil {
			return &ValidationError{Name: "nazev", err: fmt.Errorf(`ent: validator failed for field "Clanky.nazev": %w`, err)}
		}
	}
	if v, ok := cu.mutation.AutorID(); ok {
		if err := clanky.AutorIDValidator(v); err != nil {
			return &ValidationError{Name: "autor_id", err: fmt.Errorf(`ent: validator failed for field "Clanky.autor_id": %w`, err)}
		}
	}
	if cu.mutation.AutorCleared() && len(cu.mutation.AutorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Clanky.autor"`)
	}
	return nil
}

func (cu *ClankyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(clanky.Table, clanky.Columns, sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Nazev(); ok {
		_spec.SetField(clanky.FieldNazev, field.TypeString, value)
	}
	if value, ok := cu.mutation.Date(); ok {
		_spec.SetField(clanky.FieldDate, field.TypeTime, value)
	}
	if value, ok := cu.mutation.Verejne(); ok {
		_spec.SetField(clanky.FieldVerejne, field.TypeBool, value)
	}
	if value, ok := cu.mutation.Text(); ok {
		_spec.SetField(clanky.FieldText, field.TypeString, value)
	}
	if value, ok := cu.mutation.Image(); ok {
		_spec.SetField(clanky.FieldImage, field.TypeString, value)
	}
	if cu.mutation.ImageCleared() {
		_spec.ClearField(clanky.FieldImage, field.TypeString)
	}
	if cu.mutation.AutorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clanky.AutorTable,
			Columns: []string{clanky.AutorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.AutorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clanky.AutorTable,
			Columns: []string{clanky.AutorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clanky.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClankyUpdateOne is the builder for updating a single Clanky entity.
type ClankyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClankyMutation
}

// SetNazev sets the "nazev" field.
func (cuo *ClankyUpdateOne) SetNazev(s string) *ClankyUpdateOne {
	cuo.mutation.SetNazev(s)
	return cuo
}

// SetNillableNazev sets the "nazev" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableNazev(s *string) *ClankyUpdateOne {
	if s != nil {
		cuo.SetNazev(*s)
	}
	return cuo
}

// SetAutorID sets the "autor_id" field.
func (cuo *ClankyUpdateOne) SetAutorID(i int) *ClankyUpdateOne {
	cuo.mutation.SetAutorID(i)
	return cuo
}

// SetNillableAutorID sets the "autor_id" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableAutorID(i *int) *ClankyUpdateOne {
	if i != nil {
		cuo.SetAutorID(*i)
	}
	return cuo
}

// SetDate sets the "date" field.
func (cuo *ClankyUpdateOne) SetDate(t time.Time) *ClankyUpdateOne {
	cuo.mutation.SetDate(t)
	return cuo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableDate(t *time.Time) *ClankyUpdateOne {
	if t != nil {
		cuo.SetDate(*t)
	}
	return cuo
}

// SetVerejne sets the "verejne" field.
func (cuo *ClankyUpdateOne) SetVerejne(b bool) *ClankyUpdateOne {
	cuo.mutation.SetVerejne(b)
	return cuo
}

// SetNillableVerejne sets the "verejne" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableVerejne(b *bool) *ClankyUpdateOne {
	if b != nil {
		cuo.SetVerejne(*b)
	}
	return cuo
}

// SetText sets the "text" field.
func (cuo *ClankyUpdateOne) SetText(s string) *ClankyUpdateOne {
	cuo.mutation.SetText(s)
	return cuo
}

// SetNillableText sets the "text" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableText(s *string) *ClankyUpdateOne {
	if s != nil {
		cuo.SetText(*s)
	}
	return cuo
}

// SetImage sets the "image" field.
func (cuo *ClankyUpdateOne) SetImage(s string) *ClankyUpdateOne {
	cuo.mutation.SetImage(s)
	return cuo
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (cuo *ClankyUpdateOne) SetNillableImage(s *string) *ClankyUpdateOne {
	if s != nil {
		cuo.SetImage(*s)
	}
	return cuo
}

// ClearImage clears the value of the "image" field.
func (cuo *ClankyUpdateOne) ClearImage() *ClankyUpdateOne {
	cuo.mutation.ClearImage()
	return cuo
}

// SetAutor sets the "autor" edge to the User entity.
func (cuo *ClankyUpdateOne) SetAutor(u *User) *ClankyUpdateOne {
	return cuo.SetAutorID(u.ID)
}

// Mutation returns the ClankyMutation object of the builder.
func (cuo *ClankyUpdateOne) Mutation() *ClankyMutation {
	return cuo.mutation
}

// ClearAutor clears the "autor" edge to the User entity.
func (cuo *ClankyUpdateOne) ClearAutor() *ClankyUpdateOne {
	cuo.mutation.ClearAutor()
	return cuo
}

// Where appends a list predicates to the ClankyUpdate builder.
func (cuo *ClankyUpdateOne) Where(ps ...predicate.Clanky) *ClankyUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClankyUpdateOne) Select(field string, fields ...string) *ClankyUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Clanky entity.
func (cuo *ClankyUpdateOne) Save(ctx context.Context) (*Clanky, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClankyUpdateOne) SaveX(ctx context.Context) *Clanky {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClankyUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClankyUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClankyUpdateOne) check() error {
	if v, ok := cuo.mutation.Nazev(); ok {
		if err := clanky.NazevValidator(v); err != nil {
			return &ValidationError{Name: "nazev", err: fmt.Errorf(`ent: validator failed for field "Clanky.nazev": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.AutorID(); ok {
		if err := clanky.AutorIDValidator(v); err != nil {
			return &ValidationError{Name: "autor_id", err: fmt.Errorf(`ent: validator failed for field "Clanky.autor_id": %w`, err)}
		}
	}
	if cuo.mutation.AutorCleared() && len(cuo.mutation.AutorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Clanky.autor"`)
	}
	return nil
}

func (cuo *ClankyUpdateOne) sqlSave(ctx context.Context) (_node *Clanky, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clanky.Table, clanky.Columns, sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Clanky.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clanky.FieldID)
		for _, f := range fields {
			if !clanky.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clanky.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Nazev(); ok {
		_spec.SetField(clanky.FieldNazev, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Date(); ok {
		_spec.SetField(clanky.FieldDate, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.Verejne(); ok {
		_spec.SetField(clanky.FieldVerejne, field.TypeBool, value)
	}
	if value, ok := cuo.mutation.Text(); ok {
		_spec.SetField(clanky.FieldText, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Image(); ok {
		_spec.SetField(clanky.FieldImage, field.TypeString, value)
	}
	if cuo.mutation.ImageCleared() {
		_spec.ClearField(clanky.FieldImage, field.TypeString)
	}
	if cuo.mutation.AutorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clanky.AutorTable,
			Columns: []string{clanky.AutorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.AutorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clanky.AutorTable,
			Columns: []string{clanky.AutorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Clanky{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clanky.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
