// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClankyCreate is the builder for creating a Clanky entity.
type ClankyCreate struct {
	config
	mutation *ClankyMutation
	hooks    []Hook
}

// SetNazev sets the "nazev" field.
func (cc *ClankyCreate) SetNazev(s string) *ClankyCreate {
	cc.mutation.SetNazev(s)
	return cc
}

// SetTyp sets the "typ" field.
func (cc *ClankyCreate) SetTyp(i int) *ClankyCreate {
	cc.mutation.SetTyp(i)
	return cc
}

// SetAutorID sets the "autor_id" field.
func (cc *ClankyCreate) SetAutorID(i int) *ClankyCreate {
	cc.mutation.SetAutorID(i)
	return cc
}

// SetDate sets the "date" field.
func (cc *ClankyCreate) SetDate(t time.Time) *ClankyCreate {
	cc.mutation.SetDate(t)
	return cc
}

// SetVerejne sets the "verejne" field.
func (cc *ClankyCreate) SetVerejne(b bool) *ClankyCreate {
	cc.mutation.SetVerejne(b)
	return cc
}

// SetText sets the "text" field.
func (cc *ClankyCreate) SetText(s string) *ClankyCreate {
	cc.mutation.SetText(s)
	return cc
}

// SetImage sets the "image" field.
func (cc *ClankyCreate) SetImage(s string) *ClankyCreate {
	cc.mutation.SetImage(s)
	return cc
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (cc *ClankyCreate) SetNillableImage(s *string) *ClankyCreate {
	if s != nil {
		cc.SetImage(*s)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *ClankyCreate) SetID(i int) *ClankyCreate {
	cc.mutation.SetID(i)
	return cc
}

// SetAutor sets the "autor" edge to the User entity.
func (cc *ClankyCreate) SetAutor(u *User) *ClankyCreate {
	return cc.SetAutorID(u.ID)
}

// Mutation returns the ClankyMutation object of the builder.
func (cc *ClankyCreate) Mutation() *ClankyMutation {
	return cc.mutation
}

// Save creates the Clanky in the database.
func (cc *ClankyCreate) Save(ctx context.Context) (*Clanky, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClankyCreate) SaveX(ctx context.Context) *Clanky {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ClankyCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ClankyCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ClankyCreate) check() error {
	if _, ok := cc.mutation.Nazev(); !ok {
		return &ValidationError{Name: "nazev", err: errors.New(`ent: missing required field "Clanky.nazev"`)}
	}
	if v, ok := cc.mutation.Nazev(); ok {
		if err := clanky.NazevValidator(v); err != nil {
			return &ValidationError{Name: "nazev", err: fmt.Errorf(`ent: validator failed for field "Clanky.nazev": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Typ(); !ok {
		return &ValidationError{Name: "typ", err: errors.New(`ent: missing required field "Clanky.typ"`)}
	}
	if _, ok := cc.mutation.AutorID(); !ok {
		return &ValidationError{Name: "autor_id", err: errors.New(`ent: missing required field "Clanky.autor_id"`)}
	}
	if v, ok := cc.mutation.AutorID(); ok {
		if err := clanky.AutorIDValidator(v); err != nil {
			return &ValidationError{Name: "autor_id", err: fmt.Errorf(`ent: validator failed for field "Clanky.autor_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Clanky.date"`)}
	}
	if _, ok := cc.mutation.Verejne(); !ok {
		return &ValidationError{Name: "verejne", err: errors.New(`ent: missing required field "Clanky.verejne"`)}
	}
	if _, ok := cc.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Clanky.text"`)}
	}
	if v, ok := cc.mutation.ID(); ok {
		if err := clanky.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Clanky.id": %w`, err)}
		}
	}
	if len(cc.mutation.AutorIDs()) == 0 {
		return &ValidationError{Name: "autor", err: errors.New(`ent: missing required edge "Clanky.autor"`)}
	}
	return nil
}

func (cc *ClankyCreate) sqlSave(ctx context.Context) (*Clanky, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ClankyCreate) createSpec() (*Clanky, *sqlgraph.CreateSpec) {
	var (
		_node = &Clanky{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(clanky.Table, sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Nazev(); ok {
		_spec.SetField(clanky.FieldNazev, field.TypeString, value)
		_node.Nazev = value
	}
	if value, ok := cc.mutation.Typ(); ok {
		_spec.SetField(clanky.FieldTyp, field.TypeInt, value)
		_node.Typ = value
	}
	if value, ok := cc.mutation.Date(); ok {
		_spec.SetField(clanky.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := cc.mutation.Verejne(); ok {
		_spec.SetField(clanky.FieldVerejne, field.TypeBool, value)
		_node.Verejne = value
	}
	if value, ok := cc.mutation.Text(); ok {
		_spec.SetField(clanky.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := cc.mutation.Image(); ok {
		_spec.SetField(clanky.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if nodes := cc.mutation.AutorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clanky.AutorTable,
			Columns: []string{clanky.AutorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AutorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClankyCreateBulk is the builder for creating many Clanky entities in bulk.
type ClankyCreateBulk struct {
	config
	err      error
	builders []*ClankyCreate
}

// Save creates the Clanky entities in the database.
func (ccb *ClankyCreateBulk) Save(ctx context.Context) ([]*Clanky, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Clanky, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClankyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ClankyCreateBulk) SaveX(ctx context.Context) []*Clanky {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ClankyCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ClankyCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
