// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/predicate"
	"api/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClankyQuery is the builder for querying Clanky entities.
type ClankyQuery struct {
	config
	ctx        *QueryContext
	order      []clanky.OrderOption
	inters     []Interceptor
	predicates []predicate.Clanky
	withAutor  *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ClankyQuery builder.
func (cq *ClankyQuery) Where(ps ...predicate.Clanky) *ClankyQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *ClankyQuery) Limit(limit int) *ClankyQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *ClankyQuery) Offset(offset int) *ClankyQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *ClankyQuery) Unique(unique bool) *ClankyQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *ClankyQuery) Order(o ...clanky.OrderOption) *ClankyQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryAutor chains the current query on the "autor" edge.
func (cq *ClankyQuery) QueryAutor() *UserQuery {
	query := (&UserClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(clanky.Table, clanky.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, clanky.AutorTable, clanky.AutorColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Clanky entity from the query.
// Returns a *NotFoundError when no Clanky was found.
func (cq *ClankyQuery) First(ctx context.Context) (*Clanky, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{clanky.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *ClankyQuery) FirstX(ctx context.Context) *Clanky {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Clanky ID from the query.
// Returns a *NotFoundError when no Clanky ID was found.
func (cq *ClankyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{clanky.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *ClankyQuery) FirstIDX(ctx context.Context) int {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Clanky entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Clanky entity is found.
// Returns a *NotFoundError when no Clanky entities are found.
func (cq *ClankyQuery) Only(ctx context.Context) (*Clanky, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{clanky.Label}
	default:
		return nil, &NotSingularError{clanky.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *ClankyQuery) OnlyX(ctx context.Context) *Clanky {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Clanky ID in the query.
// Returns a *NotSingularError when more than one Clanky ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *ClankyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{clanky.Label}
	default:
		err = &NotSingularError{clanky.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *ClankyQuery) OnlyIDX(ctx context.Context) int {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Clankies.
func (cq *ClankyQuery) All(ctx context.Context) ([]*Clanky, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryAll)
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Clanky, *ClankyQuery]()
	return withInterceptors[[]*Clanky](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *ClankyQuery) AllX(ctx context.Context) []*Clanky {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Clanky IDs.
func (cq *ClankyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryIDs)
	if err = cq.Select(clanky.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *ClankyQuery) IDsX(ctx context.Context) []int {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *ClankyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryCount)
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*ClankyQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *ClankyQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *ClankyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, ent.OpQueryExist)
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *ClankyQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ClankyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *ClankyQuery) Clone() *ClankyQuery {
	if cq == nil {
		return nil
	}
	return &ClankyQuery{
		config:     cq.config,
		ctx:        cq.ctx.Clone(),
		order:      append([]clanky.OrderOption{}, cq.order...),
		inters:     append([]Interceptor{}, cq.inters...),
		predicates: append([]predicate.Clanky{}, cq.predicates...),
		withAutor:  cq.withAutor.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithAutor tells the query-builder to eager-load the nodes that are connected to
// the "autor" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *ClankyQuery) WithAutor(opts ...func(*UserQuery)) *ClankyQuery {
	query := (&UserClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withAutor = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Nazev string `json:"nazev,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Clanky.Query().
//		GroupBy(clanky.FieldNazev).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *ClankyQuery) GroupBy(field string, fields ...string) *ClankyGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ClankyGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = clanky.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Nazev string `json:"nazev,omitempty"`
//	}
//
//	client.Clanky.Query().
//		Select(clanky.FieldNazev).
//		Scan(ctx, &v)
func (cq *ClankyQuery) Select(fields ...string) *ClankySelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &ClankySelect{ClankyQuery: cq}
	sbuild.label = clanky.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ClankySelect configured with the given aggregations.
func (cq *ClankyQuery) Aggregate(fns ...AggregateFunc) *ClankySelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *ClankyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !clanky.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *ClankyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Clanky, error) {
	var (
		nodes       = []*Clanky{}
		_spec       = cq.querySpec()
		loadedTypes = [1]bool{
			cq.withAutor != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Clanky).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Clanky{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withAutor; query != nil {
		if err := cq.loadAutor(ctx, query, nodes, nil,
			func(n *Clanky, e *User) { n.Edges.Autor = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *ClankyQuery) loadAutor(ctx context.Context, query *UserQuery, nodes []*Clanky, init func(*Clanky), assign func(*Clanky, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Clanky)
	for i := range nodes {
		fk := nodes[i].AutorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "autor_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cq *ClankyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *ClankyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(clanky.Table, clanky.Columns, sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clanky.FieldID)
		for i := range fields {
			if fields[i] != clanky.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if cq.withAutor != nil {
			_spec.Node.AddColumnOnce(clanky.FieldAutorID)
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *ClankyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(clanky.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = clanky.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ClankyGroupBy is the group-by builder for Clanky entities.
type ClankyGroupBy struct {
	selector
	build *ClankyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *ClankyGroupBy) Aggregate(fns ...AggregateFunc) *ClankyGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *ClankyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, ent.OpQueryGroupBy)
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClankyQuery, *ClankyGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *ClankyGroupBy) sqlScan(ctx context.Context, root *ClankyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ClankySelect is the builder for selecting fields of Clanky entities.
type ClankySelect struct {
	*ClankyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *ClankySelect) Aggregate(fns ...AggregateFunc) *ClankySelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *ClankySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, ent.OpQuerySelect)
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ClankyQuery, *ClankySelect](ctx, cs.ClankyQuery, cs, cs.inters, v)
}

func (cs *ClankySelect) sqlScan(ctx context.Context, root *ClankyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
