// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Clanky is the model entity for the Clanky schema.
type Clanky struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Nazev holds the value of the "nazev" field.
	Nazev string `json:"nazev,omitempty"`
	// Typ holds the value of the "typ" field.
	Typ int `json:"typ,omitempty"`
	// AutorID holds the value of the "autor_id" field.
	AutorID int `json:"autor_id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Verejne holds the value of the "verejne" field.
	Verejne bool `json:"verejne,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClankyQuery when eager-loading is set.
	Edges        ClankyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClankyEdges holds the relations/edges for other nodes in the graph.
type ClankyEdges struct {
	// Autor holds the value of the autor edge.
	Autor *User `json:"autor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AutorOrErr returns the Autor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClankyEdges) AutorOrErr() (*User, error) {
	if e.Autor != nil {
		return e.Autor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "autor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Clanky) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clanky.FieldVerejne:
			values[i] = new(sql.NullBool)
		case clanky.FieldID, clanky.FieldTyp, clanky.FieldAutorID:
			values[i] = new(sql.NullInt64)
		case clanky.FieldNazev, clanky.FieldText, clanky.FieldImage:
			values[i] = new(sql.NullString)
		case clanky.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Clanky fields.
func (c *Clanky) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clanky.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case clanky.FieldNazev:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nazev", values[i])
			} else if value.Valid {
				c.Nazev = value.String
			}
		case clanky.FieldTyp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field typ", values[i])
			} else if value.Valid {
				c.Typ = int(value.Int64)
			}
		case clanky.FieldAutorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field autor_id", values[i])
			} else if value.Valid {
				c.AutorID = int(value.Int64)
			}
		case clanky.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				c.Date = value.Time
			}
		case clanky.FieldVerejne:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field verejne", values[i])
			} else if value.Valid {
				c.Verejne = value.Bool
			}
		case clanky.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				c.Text = value.String
			}
		case clanky.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				c.Image = value.String
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Clanky.
// This includes values selected through modifiers, order, etc.
func (c *Clanky) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// QueryAutor queries the "autor" edge of the Clanky entity.
func (c *Clanky) QueryAutor() *UserQuery {
	return NewClankyClient(c.config).QueryAutor(c)
}

// Update returns a builder for updating this Clanky.
// Note that you need to call Clanky.Unwrap() before calling this method if this Clanky
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Clanky) Update() *ClankyUpdateOne {
	return NewClankyClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Clanky entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Clanky) Unwrap() *Clanky {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Clanky is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Clanky) String() string {
	var builder strings.Builder
	builder.WriteString("Clanky(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("nazev=")
	builder.WriteString(c.Nazev)
	builder.WriteString(", ")
	builder.WriteString("typ=")
	builder.WriteString(fmt.Sprintf("%v", c.Typ))
	builder.WriteString(", ")
	builder.WriteString("autor_id=")
	builder.WriteString(fmt.Sprintf("%v", c.AutorID))
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(c.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("verejne=")
	builder.WriteString(fmt.Sprintf("%v", c.Verejne))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(c.Text)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(c.Image)
	builder.WriteByte(')')
	return builder.String()
}

// Clankies is a parsable slice of Clanky.
type Clankies []*Clanky
