// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/predicate"
	"api/ent/setting"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeClanky  = "Clanky"
	TypeSetting = "Setting"
	TypeUser    = "User"
)

// ClankyMutation represents an operation that mutates the Clanky nodes in the graph.
type ClankyMutation struct {
	config
	op            Op
	typ           string
	id            *int
	nazev         *string
	_typ          *int
	add_typ       *int
	date          *time.Time
	verejne       *bool
	text          *string
	image         *string
	clearedFields map[string]struct{}
	autor         *int
	clearedautor  bool
	done          bool
	oldValue      func(context.Context) (*Clanky, error)
	predicates    []predicate.Clanky
}

var _ ent.Mutation = (*ClankyMutation)(nil)

// clankyOption allows management of the mutation configuration using functional options.
type clankyOption func(*ClankyMutation)

// newClankyMutation creates new mutation for the Clanky entity.
func newClankyMutation(c config, op Op, opts ...clankyOption) *ClankyMutation {
	m := &ClankyMutation{
		config:        c,
		op:            op,
		typ:           TypeClanky,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withClankyID sets the ID field of the mutation.
func withClankyID(id int) clankyOption {
	return func(m *ClankyMutation) {
		var (
			err   error
			once  sync.Once
			value *Clanky
		)
		m.oldValue = func(ctx context.Context) (*Clanky, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Clanky.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withClanky sets the old Clanky of the mutation.
func withClanky(node *Clanky) clankyOption {
	return func(m *ClankyMutation) {
		m.oldValue = func(context.Context) (*Clanky, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ClankyMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ClankyMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Clanky entities.
func (m *ClankyMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ClankyMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ClankyMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Clanky.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetNazev sets the "nazev" field.
func (m *ClankyMutation) SetNazev(s string) {
	m.nazev = &s
}

// Nazev returns the value of the "nazev" field in the mutation.
func (m *ClankyMutation) Nazev() (r string, exists bool) {
	v := m.nazev
	if v == nil {
		return
	}
	return *v, true
}

// OldNazev returns the old "nazev" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldNazev(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNazev is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNazev requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNazev: %w", err)
	}
	return oldValue.Nazev, nil
}

// ResetNazev resets all changes to the "nazev" field.
func (m *ClankyMutation) ResetNazev() {
	m.nazev = nil
}

// SetTyp sets the "typ" field.
func (m *ClankyMutation) SetTyp(i int) {
	m._typ = &i
	m.add_typ = nil
}

// Typ returns the value of the "typ" field in the mutation.
func (m *ClankyMutation) Typ() (r int, exists bool) {
	v := m._typ
	if v == nil {
		return
	}
	return *v, true
}

// OldTyp returns the old "typ" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldTyp(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTyp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTyp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTyp: %w", err)
	}
	return oldValue.Typ, nil
}

// AddTyp adds i to the "typ" field.
func (m *ClankyMutation) AddTyp(i int) {
	if m.add_typ != nil {
		*m.add_typ += i
	} else {
		m.add_typ = &i
	}
}

// AddedTyp returns the value that was added to the "typ" field in this mutation.
func (m *ClankyMutation) AddedTyp() (r int, exists bool) {
	v := m.add_typ
	if v == nil {
		return
	}
	return *v, true
}

// ResetTyp resets all changes to the "typ" field.
func (m *ClankyMutation) ResetTyp() {
	m._typ = nil
	m.add_typ = nil
}

// SetAutorID sets the "autor_id" field.
func (m *ClankyMutation) SetAutorID(i int) {
	m.autor = &i
}

// AutorID returns the value of the "autor_id" field in the mutation.
func (m *ClankyMutation) AutorID() (r int, exists bool) {
	v := m.autor
	if v == nil {
		return
	}
	return *v, true
}

// OldAutorID returns the old "autor_id" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldAutorID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAutorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAutorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAutorID: %w", err)
	}
	return oldValue.AutorID, nil
}

// ResetAutorID resets all changes to the "autor_id" field.
func (m *ClankyMutation) ResetAutorID() {
	m.autor = nil
}

// SetDate sets the "date" field.
func (m *ClankyMutation) SetDate(t time.Time) {
	m.date = &t
}

// Date returns the value of the "date" field in the mutation.
func (m *ClankyMutation) Date() (r time.Time, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldDate(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *ClankyMutation) ResetDate() {
	m.date = nil
}

// SetVerejne sets the "verejne" field.
func (m *ClankyMutation) SetVerejne(b bool) {
	m.verejne = &b
}

// Verejne returns the value of the "verejne" field in the mutation.
func (m *ClankyMutation) Verejne() (r bool, exists bool) {
	v := m.verejne
	if v == nil {
		return
	}
	return *v, true
}

// OldVerejne returns the old "verejne" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldVerejne(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVerejne is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVerejne requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVerejne: %w", err)
	}
	return oldValue.Verejne, nil
}

// ResetVerejne resets all changes to the "verejne" field.
func (m *ClankyMutation) ResetVerejne() {
	m.verejne = nil
}

// SetText sets the "text" field.
func (m *ClankyMutation) SetText(s string) {
	m.text = &s
}

// Text returns the value of the "text" field in the mutation.
func (m *ClankyMutation) Text() (r string, exists bool) {
	v := m.text
	if v == nil {
		return
	}
	return *v, true
}

// OldText returns the old "text" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldText(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldText is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldText requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldText: %w", err)
	}
	return oldValue.Text, nil
}

// ResetText resets all changes to the "text" field.
func (m *ClankyMutation) ResetText() {
	m.text = nil
}

// SetImage sets the "image" field.
func (m *ClankyMutation) SetImage(s string) {
	m.image = &s
}

// Image returns the value of the "image" field in the mutation.
func (m *ClankyMutation) Image() (r string, exists bool) {
	v := m.image
	if v == nil {
		return
	}
	return *v, true
}

// OldImage returns the old "image" field's value of the Clanky entity.
// If the Clanky object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ClankyMutation) OldImage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldImage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldImage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldImage: %w", err)
	}
	return oldValue.Image, nil
}

// ClearImage clears the value of the "image" field.
func (m *ClankyMutation) ClearImage() {
	m.image = nil
	m.clearedFields[clanky.FieldImage] = struct{}{}
}

// ImageCleared returns if the "image" field was cleared in this mutation.
func (m *ClankyMutation) ImageCleared() bool {
	_, ok := m.clearedFields[clanky.FieldImage]
	return ok
}

// ResetImage resets all changes to the "image" field.
func (m *ClankyMutation) ResetImage() {
	m.image = nil
	delete(m.clearedFields, clanky.FieldImage)
}

// ClearAutor clears the "autor" edge to the User entity.
func (m *ClankyMutation) ClearAutor() {
	m.clearedautor = true
	m.clearedFields[clanky.FieldAutorID] = struct{}{}
}

// AutorCleared reports if the "autor" edge to the User entity was cleared.
func (m *ClankyMutation) AutorCleared() bool {
	return m.clearedautor
}

// AutorIDs returns the "autor" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// AutorID instead. It exists only for internal usage by the builders.
func (m *ClankyMutation) AutorIDs() (ids []int) {
	if id := m.autor; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetAutor resets all changes to the "autor" edge.
func (m *ClankyMutation) ResetAutor() {
	m.autor = nil
	m.clearedautor = false
}

// Where appends a list predicates to the ClankyMutation builder.
func (m *ClankyMutation) Where(ps ...predicate.Clanky) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ClankyMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ClankyMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Clanky, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ClankyMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ClankyMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Clanky).
func (m *ClankyMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ClankyMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.nazev != nil {
		fields = append(fields, clanky.FieldNazev)
	}
	if m._typ != nil {
		fields = append(fields, clanky.FieldTyp)
	}
	if m.autor != nil {
		fields = append(fields, clanky.FieldAutorID)
	}
	if m.date != nil {
		fields = append(fields, clanky.FieldDate)
	}
	if m.verejne != nil {
		fields = append(fields, clanky.FieldVerejne)
	}
	if m.text != nil {
		fields = append(fields, clanky.FieldText)
	}
	if m.image != nil {
		fields = append(fields, clanky.FieldImage)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ClankyMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case clanky.FieldNazev:
		return m.Nazev()
	case clanky.FieldTyp:
		return m.Typ()
	case clanky.FieldAutorID:
		return m.AutorID()
	case clanky.FieldDate:
		return m.Date()
	case clanky.FieldVerejne:
		return m.Verejne()
	case clanky.FieldText:
		return m.Text()
	case clanky.FieldImage:
		return m.Image()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ClankyMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case clanky.FieldNazev:
		return m.OldNazev(ctx)
	case clanky.FieldTyp:
		return m.OldTyp(ctx)
	case clanky.FieldAutorID:
		return m.OldAutorID(ctx)
	case clanky.FieldDate:
		return m.OldDate(ctx)
	case clanky.FieldVerejne:
		return m.OldVerejne(ctx)
	case clanky.FieldText:
		return m.OldText(ctx)
	case clanky.FieldImage:
		return m.OldImage(ctx)
	}
	return nil, fmt.Errorf("unknown Clanky field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ClankyMutation) SetField(name string, value ent.Value) error {
	switch name {
	case clanky.FieldNazev:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNazev(v)
		return nil
	case clanky.FieldTyp:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTyp(v)
		return nil
	case clanky.FieldAutorID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAutorID(v)
		return nil
	case clanky.FieldDate:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case clanky.FieldVerejne:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVerejne(v)
		return nil
	case clanky.FieldText:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetText(v)
		return nil
	case clanky.FieldImage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetImage(v)
		return nil
	}
	return fmt.Errorf("unknown Clanky field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ClankyMutation) AddedFields() []string {
	var fields []string
	if m.add_typ != nil {
		fields = append(fields, clanky.FieldTyp)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ClankyMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case clanky.FieldTyp:
		return m.AddedTyp()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ClankyMutation) AddField(name string, value ent.Value) error {
	switch name {
	case clanky.FieldTyp:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTyp(v)
		return nil
	}
	return fmt.Errorf("unknown Clanky numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ClankyMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(clanky.FieldImage) {
		fields = append(fields, clanky.FieldImage)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ClankyMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ClankyMutation) ClearField(name string) error {
	switch name {
	case clanky.FieldImage:
		m.ClearImage()
		return nil
	}
	return fmt.Errorf("unknown Clanky nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ClankyMutation) ResetField(name string) error {
	switch name {
	case clanky.FieldNazev:
		m.ResetNazev()
		return nil
	case clanky.FieldTyp:
		m.ResetTyp()
		return nil
	case clanky.FieldAutorID:
		m.ResetAutorID()
		return nil
	case clanky.FieldDate:
		m.ResetDate()
		return nil
	case clanky.FieldVerejne:
		m.ResetVerejne()
		return nil
	case clanky.FieldText:
		m.ResetText()
		return nil
	case clanky.FieldImage:
		m.ResetImage()
		return nil
	}
	return fmt.Errorf("unknown Clanky field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ClankyMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.autor != nil {
		edges = append(edges, clanky.EdgeAutor)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ClankyMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case clanky.EdgeAutor:
		if id := m.autor; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ClankyMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ClankyMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ClankyMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedautor {
		edges = append(edges, clanky.EdgeAutor)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ClankyMutation) EdgeCleared(name string) bool {
	switch name {
	case clanky.EdgeAutor:
		return m.clearedautor
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ClankyMutation) ClearEdge(name string) error {
	switch name {
	case clanky.EdgeAutor:
		m.ClearAutor()
		return nil
	}
	return fmt.Errorf("unknown Clanky unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ClankyMutation) ResetEdge(name string) error {
	switch name {
	case clanky.EdgeAutor:
		m.ResetAutor()
		return nil
	}
	return fmt.Errorf("unknown Clanky edge %s", name)
}

// SettingMutation represents an operation that mutates the Setting nodes in the graph.
type SettingMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	value         *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Setting, error)
	predicates    []predicate.Setting
}

var _ ent.Mutation = (*SettingMutation)(nil)

// settingOption allows management of the mutation configuration using functional options.
type settingOption func(*SettingMutation)

// newSettingMutation creates new mutation for the Setting entity.
func newSettingMutation(c config, op Op, opts ...settingOption) *SettingMutation {
	m := &SettingMutation{
		config:        c,
		op:            op,
		typ:           TypeSetting,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSettingID sets the ID field of the mutation.
func withSettingID(id int) settingOption {
	return func(m *SettingMutation) {
		var (
			err   error
			once  sync.Once
			value *Setting
		)
		m.oldValue = func(ctx context.Context) (*Setting, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Setting.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSetting sets the old Setting of the mutation.
func withSetting(node *Setting) settingOption {
	return func(m *SettingMutation) {
		m.oldValue = func(context.Context) (*Setting, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SettingMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SettingMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Setting entities.
func (m *SettingMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SettingMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SettingMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Setting.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SettingMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SettingMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Setting entity.
// If the Setting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SettingMutation) ResetName() {
	m.name = nil
}

// SetValue sets the "value" field.
func (m *SettingMutation) SetValue(s string) {
	m.value = &s
}

// Value returns the value of the "value" field in the mutation.
func (m *SettingMutation) Value() (r string, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Setting entity.
// If the Setting object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SettingMutation) OldValue(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// ClearValue clears the value of the "value" field.
func (m *SettingMutation) ClearValue() {
	m.value = nil
	m.clearedFields[setting.FieldValue] = struct{}{}
}

// ValueCleared returns if the "value" field was cleared in this mutation.
func (m *SettingMutation) ValueCleared() bool {
	_, ok := m.clearedFields[setting.FieldValue]
	return ok
}

// ResetValue resets all changes to the "value" field.
func (m *SettingMutation) ResetValue() {
	m.value = nil
	delete(m.clearedFields, setting.FieldValue)
}

// Where appends a list predicates to the SettingMutation builder.
func (m *SettingMutation) Where(ps ...predicate.Setting) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SettingMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SettingMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Setting, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SettingMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SettingMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Setting).
func (m *SettingMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SettingMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, setting.FieldName)
	}
	if m.value != nil {
		fields = append(fields, setting.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SettingMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case setting.FieldName:
		return m.Name()
	case setting.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SettingMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case setting.FieldName:
		return m.OldName(ctx)
	case setting.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Setting field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingMutation) SetField(name string, value ent.Value) error {
	switch name {
	case setting.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case setting.FieldValue:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Setting field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SettingMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SettingMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SettingMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Setting numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SettingMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(setting.FieldValue) {
		fields = append(fields, setting.FieldValue)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SettingMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SettingMutation) ClearField(name string) error {
	switch name {
	case setting.FieldValue:
		m.ClearValue()
		return nil
	}
	return fmt.Errorf("unknown Setting nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SettingMutation) ResetField(name string) error {
	switch name {
	case setting.FieldName:
		m.ResetName()
		return nil
	case setting.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Setting field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SettingMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SettingMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SettingMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SettingMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SettingMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SettingMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SettingMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Setting unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SettingMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Setting edge %s", name)
}

// UserMutation represents an operation that mutates the User nodes in the graph.
type UserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	username      *string
	email         *string
	name_first    *string
	name_last     *string
	password      *string
	deleted       *bool
	root_admin    *int
	addroot_admin *int
	clearedFields map[string]struct{}
	clanky        map[int]struct{}
	removedclanky map[int]struct{}
	clearedclanky bool
	done          bool
	oldValue      func(context.Context) (*User, error)
	predicates    []predicate.User
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows management of the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for the User entity.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the ID field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of User entities.
func (m *UserMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *UserMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().User.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUsername sets the "username" field.
func (m *UserMutation) SetUsername(s string) {
	m.username = &s
}

// Username returns the value of the "username" field in the mutation.
func (m *UserMutation) Username() (r string, exists bool) {
	v := m.username
	if v == nil {
		return
	}
	return *v, true
}

// OldUsername returns the old "username" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldUsername(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUsername is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUsername requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUsername: %w", err)
	}
	return oldValue.Username, nil
}

// ResetUsername resets all changes to the "username" field.
func (m *UserMutation) ResetUsername() {
	m.username = nil
}

// SetEmail sets the "email" field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// SetNameFirst sets the "name_first" field.
func (m *UserMutation) SetNameFirst(s string) {
	m.name_first = &s
}

// NameFirst returns the value of the "name_first" field in the mutation.
func (m *UserMutation) NameFirst() (r string, exists bool) {
	v := m.name_first
	if v == nil {
		return
	}
	return *v, true
}

// OldNameFirst returns the old "name_first" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldNameFirst(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNameFirst is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNameFirst requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNameFirst: %w", err)
	}
	return oldValue.NameFirst, nil
}

// ClearNameFirst clears the value of the "name_first" field.
func (m *UserMutation) ClearNameFirst() {
	m.name_first = nil
	m.clearedFields[user.FieldNameFirst] = struct{}{}
}

// NameFirstCleared returns if the "name_first" field was cleared in this mutation.
func (m *UserMutation) NameFirstCleared() bool {
	_, ok := m.clearedFields[user.FieldNameFirst]
	return ok
}

// ResetNameFirst resets all changes to the "name_first" field.
func (m *UserMutation) ResetNameFirst() {
	m.name_first = nil
	delete(m.clearedFields, user.FieldNameFirst)
}

// SetNameLast sets the "name_last" field.
func (m *UserMutation) SetNameLast(s string) {
	m.name_last = &s
}

// NameLast returns the value of the "name_last" field in the mutation.
func (m *UserMutation) NameLast() (r string, exists bool) {
	v := m.name_last
	if v == nil {
		return
	}
	return *v, true
}

// OldNameLast returns the old "name_last" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldNameLast(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNameLast is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNameLast requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNameLast: %w", err)
	}
	return oldValue.NameLast, nil
}

// ClearNameLast clears the value of the "name_last" field.
func (m *UserMutation) ClearNameLast() {
	m.name_last = nil
	m.clearedFields[user.FieldNameLast] = struct{}{}
}

// NameLastCleared returns if the "name_last" field was cleared in this mutation.
func (m *UserMutation) NameLastCleared() bool {
	_, ok := m.clearedFields[user.FieldNameLast]
	return ok
}

// ResetNameLast resets all changes to the "name_last" field.
func (m *UserMutation) ResetNameLast() {
	m.name_last = nil
	delete(m.clearedFields, user.FieldNameLast)
}

// SetPassword sets the "password" field.
func (m *UserMutation) SetPassword(s string) {
	m.password = &s
}

// Password returns the value of the "password" field in the mutation.
func (m *UserMutation) Password() (r string, exists bool) {
	v := m.password
	if v == nil {
		return
	}
	return *v, true
}

// OldPassword returns the old "password" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldPassword(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPassword is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPassword requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPassword: %w", err)
	}
	return oldValue.Password, nil
}

// ResetPassword resets all changes to the "password" field.
func (m *UserMutation) ResetPassword() {
	m.password = nil
}

// SetDeleted sets the "deleted" field.
func (m *UserMutation) SetDeleted(b bool) {
	m.deleted = &b
}

// Deleted returns the value of the "deleted" field in the mutation.
func (m *UserMutation) Deleted() (r bool, exists bool) {
	v := m.deleted
	if v == nil {
		return
	}
	return *v, true
}

// OldDeleted returns the old "deleted" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldDeleted(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeleted is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeleted requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeleted: %w", err)
	}
	return oldValue.Deleted, nil
}

// ResetDeleted resets all changes to the "deleted" field.
func (m *UserMutation) ResetDeleted() {
	m.deleted = nil
}

// SetRootAdmin sets the "root_admin" field.
func (m *UserMutation) SetRootAdmin(i int) {
	m.root_admin = &i
	m.addroot_admin = nil
}

// RootAdmin returns the value of the "root_admin" field in the mutation.
func (m *UserMutation) RootAdmin() (r int, exists bool) {
	v := m.root_admin
	if v == nil {
		return
	}
	return *v, true
}

// OldRootAdmin returns the old "root_admin" field's value of the User entity.
// If the User object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *UserMutation) OldRootAdmin(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRootAdmin is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRootAdmin requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRootAdmin: %w", err)
	}
	return oldValue.RootAdmin, nil
}

// AddRootAdmin adds i to the "root_admin" field.
func (m *UserMutation) AddRootAdmin(i int) {
	if m.addroot_admin != nil {
		*m.addroot_admin += i
	} else {
		m.addroot_admin = &i
	}
}

// AddedRootAdmin returns the value that was added to the "root_admin" field in this mutation.
func (m *UserMutation) AddedRootAdmin() (r int, exists bool) {
	v := m.addroot_admin
	if v == nil {
		return
	}
	return *v, true
}

// ResetRootAdmin resets all changes to the "root_admin" field.
func (m *UserMutation) ResetRootAdmin() {
	m.root_admin = nil
	m.addroot_admin = nil
}

// AddClankyIDs adds the "clanky" edge to the Clanky entity by ids.
func (m *UserMutation) AddClankyIDs(ids ...int) {
	if m.clanky == nil {
		m.clanky = make(map[int]struct{})
	}
	for i := range ids {
		m.clanky[ids[i]] = struct{}{}
	}
}

// ClearClanky clears the "clanky" edge to the Clanky entity.
func (m *UserMutation) ClearClanky() {
	m.clearedclanky = true
}

// ClankyCleared reports if the "clanky" edge to the Clanky entity was cleared.
func (m *UserMutation) ClankyCleared() bool {
	return m.clearedclanky
}

// RemoveClankyIDs removes the "clanky" edge to the Clanky entity by IDs.
func (m *UserMutation) RemoveClankyIDs(ids ...int) {
	if m.removedclanky == nil {
		m.removedclanky = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.clanky, ids[i])
		m.removedclanky[ids[i]] = struct{}{}
	}
}

// RemovedClanky returns the removed IDs of the "clanky" edge to the Clanky entity.
func (m *UserMutation) RemovedClankyIDs() (ids []int) {
	for id := range m.removedclanky {
		ids = append(ids, id)
	}
	return
}

// ClankyIDs returns the "clanky" edge IDs in the mutation.
func (m *UserMutation) ClankyIDs() (ids []int) {
	for id := range m.clanky {
		ids = append(ids, id)
	}
	return
}

// ResetClanky resets all changes to the "clanky" edge.
func (m *UserMutation) ResetClanky() {
	m.clanky = nil
	m.clearedclanky = false
	m.removedclanky = nil
}

// Where appends a list predicates to the UserMutation builder.
func (m *UserMutation) Where(ps ...predicate.User) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the UserMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *UserMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.User, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *UserMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.username != nil {
		fields = append(fields, user.FieldUsername)
	}
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	if m.name_first != nil {
		fields = append(fields, user.FieldNameFirst)
	}
	if m.name_last != nil {
		fields = append(fields, user.FieldNameLast)
	}
	if m.password != nil {
		fields = append(fields, user.FieldPassword)
	}
	if m.deleted != nil {
		fields = append(fields, user.FieldDeleted)
	}
	if m.root_admin != nil {
		fields = append(fields, user.FieldRootAdmin)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldUsername:
		return m.Username()
	case user.FieldEmail:
		return m.Email()
	case user.FieldNameFirst:
		return m.NameFirst()
	case user.FieldNameLast:
		return m.NameLast()
	case user.FieldPassword:
		return m.Password()
	case user.FieldDeleted:
		return m.Deleted()
	case user.FieldRootAdmin:
		return m.RootAdmin()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldUsername:
		return m.OldUsername(ctx)
	case user.FieldEmail:
		return m.OldEmail(ctx)
	case user.FieldNameFirst:
		return m.OldNameFirst(ctx)
	case user.FieldNameLast:
		return m.OldNameLast(ctx)
	case user.FieldPassword:
		return m.OldPassword(ctx)
	case user.FieldDeleted:
		return m.OldDeleted(ctx)
	case user.FieldRootAdmin:
		return m.OldRootAdmin(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldUsername:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUsername(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case user.FieldNameFirst:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNameFirst(v)
		return nil
	case user.FieldNameLast:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNameLast(v)
		return nil
	case user.FieldPassword:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPassword(v)
		return nil
	case user.FieldDeleted:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeleted(v)
		return nil
	case user.FieldRootAdmin:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRootAdmin(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *UserMutation) AddedFields() []string {
	var fields []string
	if m.addroot_admin != nil {
		fields = append(fields, user.FieldRootAdmin)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case user.FieldRootAdmin:
		return m.AddedRootAdmin()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	case user.FieldRootAdmin:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRootAdmin(v)
		return nil
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *UserMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(user.FieldNameFirst) {
		fields = append(fields, user.FieldNameFirst)
	}
	if m.FieldCleared(user.FieldNameLast) {
		fields = append(fields, user.FieldNameLast)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	switch name {
	case user.FieldNameFirst:
		m.ClearNameFirst()
		return nil
	case user.FieldNameLast:
		m.ClearNameLast()
		return nil
	}
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldUsername:
		m.ResetUsername()
		return nil
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	case user.FieldNameFirst:
		m.ResetNameFirst()
		return nil
	case user.FieldNameLast:
		m.ResetNameLast()
		return nil
	case user.FieldPassword:
		m.ResetPassword()
		return nil
	case user.FieldDeleted:
		m.ResetDeleted()
		return nil
	case user.FieldRootAdmin:
		m.ResetRootAdmin()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clanky != nil {
		edges = append(edges, user.EdgeClanky)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeClanky:
		ids := make([]ent.Value, 0, len(m.clanky))
		for id := range m.clanky {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedclanky != nil {
		edges = append(edges, user.EdgeClanky)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeClanky:
		ids := make([]ent.Value, 0, len(m.removedclanky))
		for id := range m.removedclanky {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedclanky {
		edges = append(edges, user.EdgeClanky)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	case user.EdgeClanky:
		return m.clearedclanky
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeClanky:
		m.ResetClanky()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
