// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/schema"
	"api/ent/setting"
	"api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	clankyFields := schema.Clanky{}.Fields()
	_ = clankyFields
	// clankyDescNazev is the schema descriptor for nazev field.
	clankyDescNazev := clankyFields[1].Descriptor()
	// clanky.NazevValidator is a validator for the "nazev" field. It is called by the builders before save.
	clanky.NazevValidator = clankyDescNazev.Validators[0].(func(string) error)
	// clankyDescAutorID is the schema descriptor for autor_id field.
	clankyDescAutorID := clankyFields[3].Descriptor()
	// clanky.AutorIDValidator is a validator for the "autor_id" field. It is called by the builders before save.
	clanky.AutorIDValidator = clankyDescAutorID.Validators[0].(func(int) error)
	// clankyDescID is the schema descriptor for id field.
	clankyDescID := clankyFields[0].Descriptor()
	// clanky.IDValidator is a validator for the "id" field. It is called by the builders before save.
	clanky.IDValidator = clankyDescID.Validators[0].(func(int) error)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescName is the schema descriptor for name field.
	settingDescName := settingFields[1].Descriptor()
	// setting.NameValidator is a validator for the "name" field. It is called by the builders before save.
	setting.NameValidator = settingDescName.Validators[0].(func(string) error)
	// settingDescID is the schema descriptor for id field.
	settingDescID := settingFields[0].Descriptor()
	// setting.IDValidator is a validator for the "id" field. It is called by the builders before save.
	setting.IDValidator = settingDescID.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[5].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescDeleted is the schema descriptor for deleted field.
	userDescDeleted := userFields[6].Descriptor()
	// user.DefaultDeleted holds the default value on creation for the deleted field.
	user.DefaultDeleted = userDescDeleted.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int) error)
}
