// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/clanky"
	"api/ent/predicate"
	"api/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.mutation.Where(ps...)
	return uu
}

// SetUsername sets the "username" field.
func (uu *UserUpdate) SetUsername(s string) *UserUpdate {
	uu.mutation.SetUsername(s)
	return uu
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (uu *UserUpdate) SetNillableUsername(s *string) *UserUpdate {
	if s != nil {
		uu.SetUsername(*s)
	}
	return uu
}

// SetEmail sets the "email" field.
func (uu *UserUpdate) SetEmail(s string) *UserUpdate {
	uu.mutation.SetEmail(s)
	return uu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uu *UserUpdate) SetNillableEmail(s *string) *UserUpdate {
	if s != nil {
		uu.SetEmail(*s)
	}
	return uu
}

// SetNameFirst sets the "name_first" field.
func (uu *UserUpdate) SetNameFirst(s string) *UserUpdate {
	uu.mutation.SetNameFirst(s)
	return uu
}

// SetNillableNameFirst sets the "name_first" field if the given value is not nil.
func (uu *UserUpdate) SetNillableNameFirst(s *string) *UserUpdate {
	if s != nil {
		uu.SetNameFirst(*s)
	}
	return uu
}

// ClearNameFirst clears the value of the "name_first" field.
func (uu *UserUpdate) ClearNameFirst() *UserUpdate {
	uu.mutation.ClearNameFirst()
	return uu
}

// SetNameLast sets the "name_last" field.
func (uu *UserUpdate) SetNameLast(s string) *UserUpdate {
	uu.mutation.SetNameLast(s)
	return uu
}

// SetNillableNameLast sets the "name_last" field if the given value is not nil.
func (uu *UserUpdate) SetNillableNameLast(s *string) *UserUpdate {
	if s != nil {
		uu.SetNameLast(*s)
	}
	return uu
}

// ClearNameLast clears the value of the "name_last" field.
func (uu *UserUpdate) ClearNameLast() *UserUpdate {
	uu.mutation.ClearNameLast()
	return uu
}

// SetPassword sets the "password" field.
func (uu *UserUpdate) SetPassword(s string) *UserUpdate {
	uu.mutation.SetPassword(s)
	return uu
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uu *UserUpdate) SetNillablePassword(s *string) *UserUpdate {
	if s != nil {
		uu.SetPassword(*s)
	}
	return uu
}

// SetDeleted sets the "deleted" field.
func (uu *UserUpdate) SetDeleted(b bool) *UserUpdate {
	uu.mutation.SetDeleted(b)
	return uu
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (uu *UserUpdate) SetNillableDeleted(b *bool) *UserUpdate {
	if b != nil {
		uu.SetDeleted(*b)
	}
	return uu
}

// SetRootAdmin sets the "root_admin" field.
func (uu *UserUpdate) SetRootAdmin(i int) *UserUpdate {
	uu.mutation.ResetRootAdmin()
	uu.mutation.SetRootAdmin(i)
	return uu
}

// SetNillableRootAdmin sets the "root_admin" field if the given value is not nil.
func (uu *UserUpdate) SetNillableRootAdmin(i *int) *UserUpdate {
	if i != nil {
		uu.SetRootAdmin(*i)
	}
	return uu
}

// AddRootAdmin adds i to the "root_admin" field.
func (uu *UserUpdate) AddRootAdmin(i int) *UserUpdate {
	uu.mutation.AddRootAdmin(i)
	return uu
}

// AddClankyIDs adds the "clanky" edge to the Clanky entity by IDs.
func (uu *UserUpdate) AddClankyIDs(ids ...int) *UserUpdate {
	uu.mutation.AddClankyIDs(ids...)
	return uu
}

// AddClanky adds the "clanky" edges to the Clanky entity.
func (uu *UserUpdate) AddClanky(c ...*Clanky) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.AddClankyIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// ClearClanky clears all "clanky" edges to the Clanky entity.
func (uu *UserUpdate) ClearClanky() *UserUpdate {
	uu.mutation.ClearClanky()
	return uu
}

// RemoveClankyIDs removes the "clanky" edge to Clanky entities by IDs.
func (uu *UserUpdate) RemoveClankyIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveClankyIDs(ids...)
	return uu
}

// RemoveClanky removes "clanky" edges to Clanky entities.
func (uu *UserUpdate) RemoveClanky(c ...*Clanky) *UserUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uu.RemoveClankyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uu.sqlSave, uu.mutation, uu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uu *UserUpdate) check() error {
	if v, ok := uu.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := uu.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	return nil
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := uu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uu.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uu.mutation.NameFirst(); ok {
		_spec.SetField(user.FieldNameFirst, field.TypeString, value)
	}
	if uu.mutation.NameFirstCleared() {
		_spec.ClearField(user.FieldNameFirst, field.TypeString)
	}
	if value, ok := uu.mutation.NameLast(); ok {
		_spec.SetField(user.FieldNameLast, field.TypeString, value)
	}
	if uu.mutation.NameLastCleared() {
		_spec.ClearField(user.FieldNameLast, field.TypeString)
	}
	if value, ok := uu.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uu.mutation.Deleted(); ok {
		_spec.SetField(user.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := uu.mutation.RootAdmin(); ok {
		_spec.SetField(user.FieldRootAdmin, field.TypeInt, value)
	}
	if value, ok := uu.mutation.AddedRootAdmin(); ok {
		_spec.AddField(user.FieldRootAdmin, field.TypeInt, value)
	}
	if uu.mutation.ClankyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.RemovedClankyIDs(); len(nodes) > 0 && !uu.mutation.ClankyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.ClankyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uu.mutation.done = true
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (uuo *UserUpdateOne) SetUsername(s string) *UserUpdateOne {
	uuo.mutation.SetUsername(s)
	return uuo
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUsername(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetUsername(*s)
	}
	return uuo
}

// SetEmail sets the "email" field.
func (uuo *UserUpdateOne) SetEmail(s string) *UserUpdateOne {
	uuo.mutation.SetEmail(s)
	return uuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableEmail(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetEmail(*s)
	}
	return uuo
}

// SetNameFirst sets the "name_first" field.
func (uuo *UserUpdateOne) SetNameFirst(s string) *UserUpdateOne {
	uuo.mutation.SetNameFirst(s)
	return uuo
}

// SetNillableNameFirst sets the "name_first" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableNameFirst(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetNameFirst(*s)
	}
	return uuo
}

// ClearNameFirst clears the value of the "name_first" field.
func (uuo *UserUpdateOne) ClearNameFirst() *UserUpdateOne {
	uuo.mutation.ClearNameFirst()
	return uuo
}

// SetNameLast sets the "name_last" field.
func (uuo *UserUpdateOne) SetNameLast(s string) *UserUpdateOne {
	uuo.mutation.SetNameLast(s)
	return uuo
}

// SetNillableNameLast sets the "name_last" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableNameLast(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetNameLast(*s)
	}
	return uuo
}

// ClearNameLast clears the value of the "name_last" field.
func (uuo *UserUpdateOne) ClearNameLast() *UserUpdateOne {
	uuo.mutation.ClearNameLast()
	return uuo
}

// SetPassword sets the "password" field.
func (uuo *UserUpdateOne) SetPassword(s string) *UserUpdateOne {
	uuo.mutation.SetPassword(s)
	return uuo
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillablePassword(s *string) *UserUpdateOne {
	if s != nil {
		uuo.SetPassword(*s)
	}
	return uuo
}

// SetDeleted sets the "deleted" field.
func (uuo *UserUpdateOne) SetDeleted(b bool) *UserUpdateOne {
	uuo.mutation.SetDeleted(b)
	return uuo
}

// SetNillableDeleted sets the "deleted" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableDeleted(b *bool) *UserUpdateOne {
	if b != nil {
		uuo.SetDeleted(*b)
	}
	return uuo
}

// SetRootAdmin sets the "root_admin" field.
func (uuo *UserUpdateOne) SetRootAdmin(i int) *UserUpdateOne {
	uuo.mutation.ResetRootAdmin()
	uuo.mutation.SetRootAdmin(i)
	return uuo
}

// SetNillableRootAdmin sets the "root_admin" field if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableRootAdmin(i *int) *UserUpdateOne {
	if i != nil {
		uuo.SetRootAdmin(*i)
	}
	return uuo
}

// AddRootAdmin adds i to the "root_admin" field.
func (uuo *UserUpdateOne) AddRootAdmin(i int) *UserUpdateOne {
	uuo.mutation.AddRootAdmin(i)
	return uuo
}

// AddClankyIDs adds the "clanky" edge to the Clanky entity by IDs.
func (uuo *UserUpdateOne) AddClankyIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddClankyIDs(ids...)
	return uuo
}

// AddClanky adds the "clanky" edges to the Clanky entity.
func (uuo *UserUpdateOne) AddClanky(c ...*Clanky) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.AddClankyIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// ClearClanky clears all "clanky" edges to the Clanky entity.
func (uuo *UserUpdateOne) ClearClanky() *UserUpdateOne {
	uuo.mutation.ClearClanky()
	return uuo
}

// RemoveClankyIDs removes the "clanky" edge to Clanky entities by IDs.
func (uuo *UserUpdateOne) RemoveClankyIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveClankyIDs(ids...)
	return uuo
}

// RemoveClanky removes "clanky" edges to Clanky entities.
func (uuo *UserUpdateOne) RemoveClanky(c ...*Clanky) *UserUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uuo.RemoveClankyIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (uuo *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	uuo.mutation.Where(ps...)
	return uuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uuo *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	uuo.fields = append([]string{field}, fields...)
	return uuo
}

// Save executes the query and returns the updated User entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, uuo.sqlSave, uuo.mutation, uuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uuo *UserUpdateOne) check() error {
	if v, ok := uuo.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := uuo.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	return nil
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := uuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uuo.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := uuo.mutation.NameFirst(); ok {
		_spec.SetField(user.FieldNameFirst, field.TypeString, value)
	}
	if uuo.mutation.NameFirstCleared() {
		_spec.ClearField(user.FieldNameFirst, field.TypeString)
	}
	if value, ok := uuo.mutation.NameLast(); ok {
		_spec.SetField(user.FieldNameLast, field.TypeString, value)
	}
	if uuo.mutation.NameLastCleared() {
		_spec.ClearField(user.FieldNameLast, field.TypeString)
	}
	if value, ok := uuo.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
	}
	if value, ok := uuo.mutation.Deleted(); ok {
		_spec.SetField(user.FieldDeleted, field.TypeBool, value)
	}
	if value, ok := uuo.mutation.RootAdmin(); ok {
		_spec.SetField(user.FieldRootAdmin, field.TypeInt, value)
	}
	if value, ok := uuo.mutation.AddedRootAdmin(); ok {
		_spec.AddField(user.FieldRootAdmin, field.TypeInt, value)
	}
	if uuo.mutation.ClankyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.RemovedClankyIDs(); len(nodes) > 0 && !uuo.mutation.ClankyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.ClankyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ClankyTable,
			Columns: []string{user.ClankyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clanky.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: uuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uuo.mutation.done = true
	return _node, nil
}
