// Code generated by ent, DO NOT EDIT.

package clanky

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the clanky type in the database.
	Label = "clanky"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNazev holds the string denoting the nazev field in the database.
	FieldNazev = "nazev"
	// FieldTyp holds the string denoting the typ field in the database.
	FieldTyp = "typ"
	// FieldAutorID holds the string denoting the autor_id field in the database.
	FieldAutorID = "autor_id"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldVerejne holds the string denoting the verejne field in the database.
	FieldVerejne = "verejne"
	// FieldText holds the string denoting the text field in the database.
	FieldText = "text"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// EdgeAutor holds the string denoting the autor edge name in mutations.
	EdgeAutor = "autor"
	// Table holds the table name of the clanky in the database.
	Table = "clankies"
	// AutorTable is the table that holds the autor relation/edge.
	AutorTable = "clankies"
	// AutorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AutorInverseTable = "users"
	// AutorColumn is the table column denoting the autor relation/edge.
	AutorColumn = "autor_id"
)

// Columns holds all SQL columns for clanky fields.
var Columns = []string{
	FieldID,
	FieldNazev,
	FieldTyp,
	FieldAutorID,
	FieldDate,
	FieldVerejne,
	FieldText,
	FieldImage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NazevValidator is a validator for the "nazev" field. It is called by the builders before save.
	NazevValidator func(string) error
	// AutorIDValidator is a validator for the "autor_id" field. It is called by the builders before save.
	AutorIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Clanky queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNazev orders the results by the nazev field.
func ByNazev(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNazev, opts...).ToFunc()
}

// ByTyp orders the results by the typ field.
func ByTyp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTyp, opts...).ToFunc()
}

// ByAutorID orders the results by the autor_id field.
func ByAutorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutorID, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByVerejne orders the results by the verejne field.
func ByVerejne(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerejne, opts...).ToFunc()
}

// ByText orders the results by the text field.
func ByText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldText, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByAutorField orders the results by autor field.
func ByAutorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAutorStep(), sql.OrderByField(field, opts...))
	}
}
func newAutorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AutorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AutorTable, AutorColumn),
	)
}
