// Code generated by ent, DO NOT EDIT.

package clanky

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldID, id))
}

// Nazev applies equality check predicate on the "nazev" field. It's identical to NazevEQ.
func Nazev(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldNazev, v))
}

// Typ applies equality check predicate on the "typ" field. It's identical to TypEQ.
func Typ(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldTyp, v))
}

// AutorID applies equality check predicate on the "autor_id" field. It's identical to AutorIDEQ.
func AutorID(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldAutorID, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldDate, v))
}

// Verejne applies equality check predicate on the "verejne" field. It's identical to VerejneEQ.
func Verejne(v bool) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldVerejne, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldText, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldImage, v))
}

// NazevEQ applies the EQ predicate on the "nazev" field.
func NazevEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldNazev, v))
}

// NazevNEQ applies the NEQ predicate on the "nazev" field.
func NazevNEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldNazev, v))
}

// NazevIn applies the In predicate on the "nazev" field.
func NazevIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldNazev, vs...))
}

// NazevNotIn applies the NotIn predicate on the "nazev" field.
func NazevNotIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldNazev, vs...))
}

// NazevGT applies the GT predicate on the "nazev" field.
func NazevGT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldNazev, v))
}

// NazevGTE applies the GTE predicate on the "nazev" field.
func NazevGTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldNazev, v))
}

// NazevLT applies the LT predicate on the "nazev" field.
func NazevLT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldNazev, v))
}

// NazevLTE applies the LTE predicate on the "nazev" field.
func NazevLTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldNazev, v))
}

// NazevContains applies the Contains predicate on the "nazev" field.
func NazevContains(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContains(FieldNazev, v))
}

// NazevHasPrefix applies the HasPrefix predicate on the "nazev" field.
func NazevHasPrefix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasPrefix(FieldNazev, v))
}

// NazevHasSuffix applies the HasSuffix predicate on the "nazev" field.
func NazevHasSuffix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasSuffix(FieldNazev, v))
}

// NazevEqualFold applies the EqualFold predicate on the "nazev" field.
func NazevEqualFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEqualFold(FieldNazev, v))
}

// NazevContainsFold applies the ContainsFold predicate on the "nazev" field.
func NazevContainsFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContainsFold(FieldNazev, v))
}

// TypEQ applies the EQ predicate on the "typ" field.
func TypEQ(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldTyp, v))
}

// TypNEQ applies the NEQ predicate on the "typ" field.
func TypNEQ(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldTyp, v))
}

// TypIn applies the In predicate on the "typ" field.
func TypIn(vs ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldTyp, vs...))
}

// TypNotIn applies the NotIn predicate on the "typ" field.
func TypNotIn(vs ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldTyp, vs...))
}

// TypGT applies the GT predicate on the "typ" field.
func TypGT(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldTyp, v))
}

// TypGTE applies the GTE predicate on the "typ" field.
func TypGTE(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldTyp, v))
}

// TypLT applies the LT predicate on the "typ" field.
func TypLT(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldTyp, v))
}

// TypLTE applies the LTE predicate on the "typ" field.
func TypLTE(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldTyp, v))
}

// AutorIDEQ applies the EQ predicate on the "autor_id" field.
func AutorIDEQ(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldAutorID, v))
}

// AutorIDNEQ applies the NEQ predicate on the "autor_id" field.
func AutorIDNEQ(v int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldAutorID, v))
}

// AutorIDIn applies the In predicate on the "autor_id" field.
func AutorIDIn(vs ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldAutorID, vs...))
}

// AutorIDNotIn applies the NotIn predicate on the "autor_id" field.
func AutorIDNotIn(vs ...int) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldAutorID, vs...))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldDate, v))
}

// VerejneEQ applies the EQ predicate on the "verejne" field.
func VerejneEQ(v bool) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldVerejne, v))
}

// VerejneNEQ applies the NEQ predicate on the "verejne" field.
func VerejneNEQ(v bool) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldVerejne, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContainsFold(FieldText, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Clanky {
	return predicate.Clanky(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.Clanky {
	return predicate.Clanky(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.Clanky {
	return predicate.Clanky(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Clanky {
	return predicate.Clanky(sql.FieldContainsFold(FieldImage, v))
}

// HasAutor applies the HasEdge predicate on the "autor" edge.
func HasAutor() predicate.Clanky {
	return predicate.Clanky(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AutorTable, AutorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAutorWith applies the HasEdge predicate on the "autor" edge with a given conditions (other predicates).
func HasAutorWith(preds ...predicate.User) predicate.Clanky {
	return predicate.Clanky(func(s *sql.Selector) {
		step := newAutorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Clanky) predicate.Clanky {
	return predicate.Clanky(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Clanky) predicate.Clanky {
	return predicate.Clanky(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Clanky) predicate.Clanky {
	return predicate.Clanky(sql.NotPredicates(p))
}
